sudo: required

language: node_js
node_js:
- "7"


before_install:
- rm -rf ~/.gnupg


before_script:
- export PLUGIN_DIR=$(pwd)
- ls -l
- sudo rm -rf /etc/mysql/
- sudo apt-get -qq purge mysql* graphviz*
- sudo apt-get -qq autoremove
- sudo apt-get update
- lsb_release -a
- sudo apt-get --only-upgrade install google-chrome-stable
- sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
- sudo wget -qO ee rt.cx/ee && sudo bash ee
- source /etc/bash_completion.d/ee_auto.rc
- sudo ee -v
- sudo lsb_release  -a
- sudo tail /var/log/ee/ee.log
- sudo ee site create wp.localtest.me --wpfc --user=ADMINUSER --email=juhi.saxena@rtcamp.com --pass=ADMINPASS
- sudo chmod 777 -R /var/www
- sudo nginx -t
- sudo service nginx reload
- cd /var/www/wp.localtest.me/htdocs/wp-content/plugins/ && ls
- wp --allow-root plugin deactivate w3-total-cache
- wp --allow-root plugin delete nginx-helper
- mkdir nginx-helper
- cd $PLUGIN_DIR
- cp -Rf * /var/www/wp.localtest.me/htdocs/wp-content/plugins/nginx-helper/
- cd /var/www/wp.localtest.me/htdocs/
- wp plugin activate --all
- cd $PLUGIN_DIR
- cd tests/functional/
- npm install -g nightwatch
- npm install

script:
- nightwatch
